# Generated by Django 3.2.13 on 2022-11-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='coast',
            new_name='cost',
        ),
        migrations.AlterField(
            model_name='store',
            name='buysell',
            field=models.BooleanField(default=False),
        ),
    ]
