# Generated by Django 3.2.13 on 2022-11-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
