# Generated by Django 3.2.13 on 2022-11-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221101_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='buysell',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
