# Generated by Django 3.2.13 on 2022-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('풀', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type1.png'), ('불', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type2.png'), ('물', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type3.png'), ('전기', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type4.png'), ('에스퍼', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('격투', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('악', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('강철', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('페어리', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('드레곤', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png'), ('노말', 'https://cards.image.pokemonkorea.co.kr/data/images/symbol/type5.png')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
