# Generated by Django 3.2.13 on 2022-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('풀', 'Grass'), ('불', 'Fire'), ('물', 'Water'), ('전기', 'Lightning'), ('에스퍼', 'Psychic'), ('격투', 'Fighting'), ('악', 'Darkness'), ('강철', 'Metal'), ('페어리', 'Fairy'), ('드레곤', 'Dragon'), ('노말', 'Colorless')], max_length=3),
        ),
    ]
