# Generated by Django 3.2.13 on 2022-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('Grass', '풀'), ('Fire', '불'), ('Water', '물'), ('Lightning', '전기'), ('Psychic', '에스퍼'), ('Fighting', '격투'), ('Darkness', '악'), ('Metal', '강철'), ('Fairy', '페어리'), ('Dragon', '드레곤'), ('Colorless', '노말')], max_length=10),
        ),
    ]
